services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: despensia-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/despensia
      SPRING_DATASOURCE_USERNAME: despensia
      SPRING_DATASOURCE_PASSWORD: despensia
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/despensia
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - despensia-net

networks:
  despensia-net:
    external: true
